#%RAML 1.0 SecurityScheme
type: OAuth 2.0
description: |
  This API supports OAuth 2.0 for authorizing requests using PingFederate.
  Please note that MuleSoft will not actually implement any OAuth 2.0 scope enforcement
  as declared with a resource & method's `securedBy` unless you apply an one or more
  relevant API Manager Policies:
    - One of the `OAuth 2.0 protected` PingFederate policies.
    - The `OAuth 2.0 scope enforcement` custom policy.
describedBy:
  headers:
    Authorization?:
      description: OAuth 2 access token. Use EITHER this or the access_token, not both.
      type: string
  queryParameters:
    access_token?:
      description: OAuth 2 access token. Use EITHER this or the Authorization header, not both.
      type: string
  responses:
    401:
      description: Bad or expired token.
    403:
      description: Bad OAuth request
settings:
  authorizationUri: https://oauth.cc.columbia.edu/as/authorization.oauth2
  accessTokenUri: https://oauth.cc.columbia.edu/as/token.oauth2
  authorizationGrants: 
    - authorization_code
    - client_credentials
  scopes: 
    !include scopes.raml
