# available scopes: this is a BUG in APIkit console. They only allow scopes that are listed here.
- openid
- create
- read
- update
- delete
- auth-columbia
- auth-facebook
- auth-google
- auth-linkedin 
- auth-twitter
- auth-windowslive
- auth-none
- demo-netphone-admin